title:          Let's Build a Compiler (in Python)!
tagline:        A non-theoretical approach to compiler development.
author:
  name:         Austin Hastings
  email:        Austin_Hastings@yahoo.com
permalink:      /:title.html

pygments:       false
exclude:        [ _config.yml, README.md ]

markdown:       redcarpet2
redcarpet:
  extensions:   [ "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data" ]


